insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (280, 2110, 3011);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (378, 4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (525, 9095, 2770);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (648,  9095, 2770);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (735,  9095, 2770);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (418,  9095, 2770);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (785,4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (893, 2110, 3011);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (930, 2110, 3011);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (869, 2110, 3011);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (673, 3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (298, 3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (897, 3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (210, 3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (873,  3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (397,  3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (923,  3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (548,  3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (831,  3601, 4307);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (93,4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (499, 4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (467, 4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (92,4295, 4751);

insert into SYS.T_EMPROLE (EMP_ID, ROLE_ID, DEPT_ID)
values (918,4295, 4751);

CREATE TABLE T_audits (
      audit_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      table_name       VARCHAR2(255),
      transaction_name VARCHAR2(10),
      by_user          VARCHAR2(30),
      transaction_date DATE
);

commit;
